### ISSUE TITLE
请问一下，那种帧动画的效果是如何实现的?

### ISSUE THREAD

**Issue by huanglins** [Eilgnaw/WidgetAnimation#1]

**Comment by Eilgnaw** [comment]
把Text(, style: .timer)盖在不同图层上面,自己制作特殊的字体文件,来控制显隐,达到一个动画效果.

**Comment by huanglins** [comment]
找到一个这个， https://github.com/NeverLand-LLT/WidgetFrameAnimation，但是使用他的字体大概过了2分钟后图片就是显示不全，我也不知道如何去修改他的字体，请问知道如何弄吗？

**Comment by huanglins** [comment]
找到一个这个， https://github.com/NeverLand-LLT/WidgetFrameAnimation。
但是使用他的字体大概过了2分钟后图片就是显示不全，我也不知道如何去修改他的字体，请问知道如何弄吗？

**Comment by huanglins** [comment]
找到一个这个， https://github.com/NeverLand-LLT/WidgetFrameAnimation
但是使用他的字体大概过了2分钟后图片就是显示不全，我也不知道如何去修改他的字体，请问知道如何弄吗？

**Comment by Eilgnaw** [comment]
不知道,我只是简单的测试过,建议你去咨询一下这个作者.
